[김해준] Add : Order App 추가
wecode-bootcamp-korea/11-KiBon-backend pull request #5
Opened 2020-08-25 05:39 UTC by hj8853

- Wishlist 구현 할 Order App 추가
- Cart Table Models.py 작성 후 commit

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-25 09:57 UTC, lordmyshepherd requested changes

2020-08-25 09:57 UTC, lordmyshepherd commented on order/models.py
> +    product_image = models.ForeignKey('product.Image', on_delete = models.CASCADE)
해준님! product_image를 product가 아니라 Cart가 가지고 있는 이유가 있나요?

2020-08-25 10:07 UTC, hj8853 commented on order/models.py
> +    product_image = models.ForeignKey('product.Image', on_delete = models.CASCADE)
Product App에서 product랑 Image table을 따로 가지고 있습니다! 
그리고 장바구니에 들어갔을 때, 상품 이미지, 이름, 수량, 가격을 표현해주어야 하는데, 그 이미지를 가져오기 위해서 위처럼 ForeignKey를 연결했습니다.

2020-08-25 13:55 UTC, hj8853 commented on order/models.py
> +    product_image = models.ForeignKey('product.Image', on_delete = models.CASCADE)
역참조 해서 사용할 수 있을 것 같네요! 거기까지 생각 못했던 것 같아서 삭제했습니다!

2020-08-26 01:12 UTC, lordmyshepherd approved these changes

2020-08-26 01:12 UTC, lordmyshepherd commented on order/models.py
> +    product       = models.ForeignKey('product.Product', on_delete = models.CASCADE)
잘 바꾸셨습니다~~~~

2020-08-26 01:15 UTC, lordmyshepherd commented
LGTM :+1:

2020-08-26 01:15 UTC, merged