[창식] product app models.py 수정, Restful API 작성, Views.py 작성완료
wecode-bootcamp-korea/11-KiBon-backend pull request #7
Opened 2020-08-26 01:30 UTC by changsikkwon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-26 01:53 UTC, changsikkwon commented
혹시 만약에 그럴일 없겠지만 merge 될 수 있는 코드라면 merge 해주시면 안됩니다!

2020-08-26 07:33 UTC, lordmyshepherd requested changes

2020-08-26 07:33 UTC, lordmyshepherd commented on product/models.py
> -class Description(models.Model):
창식님!!!
description을 빼고 HtmlTag를 넣으신 이유가 있나요??

2020-08-26 07:33 UTC, lordmyshepherd commented on product/views.py
> +        pk = request.GET.get('category', None)
창식님.... 해당 코드가 잘 동작하는지 의문이에요...
`path('/<int:pk>', ProductView.as_view()),` 에서 path parameter를 사용해서 product_id를 전달해주고 있습니다.
`pk = request.GET.get('category', None)` <<는 query parameter를 이용해서 value 값을 가져와야 합니다.

2020-08-26 07:33 UTC, lordmyshepherd commented on product/views.py
> +        except ObjectDoesNotExist:
어떤 Object가 존재하지 않는지 명확하지 않습니다.
`Category.DoesNotExist`로 변경해주세요~

2020-08-26 07:33 UTC, lordmyshepherd commented on product/views.py
> +            category = Category.objects.prefetch_related(Prefetch('product_set', queryset=Product.objects.prefetch_related('image_set'))).get(pk = pk)
이부분도 잘 동작하나요?

2020-08-26 07:34 UTC, changsikkwon commented on product/models.py
> -class Description(models.Model):
description을 사용하는 곳이없고 html 전체를 넘기기로했습니다

2020-08-26 07:51 UTC, changsikkwon commented on product/views.py
> +
Product.objects.get(product_id=pk).description.html_tag

2020-08-26 11:05 UTC, soheon-lee commented on product/views.py
> +                    "image" : product.image_set.all()[0].image_url,
```suggestion
                    "image" : product.image_set.first().image_url,
```

2020-08-26 11:05 UTC, soheon-lee commented on product/views.py
> +                    "image" : product.image_set.all()[0].image_url,
첫번째 요소만 고르는 방법에는 메소드를 활용하시는 편이 좋습니다

2020-08-26 11:46 UTC, changsikkwon commented on product/views.py
> +                    "image" : product.image_set.all()[0].image_url,
바로 수정해서 푸쉬할게용

2020-08-26 11:47 UTC, changsikkwon commented on product/views.py
> +                    "image" : product.image_set.all()[0].image_url,
감사합니다 ㅎㅎ

2020-08-27 03:25 UTC, soheon-lee commented
LGTM 👍

2020-08-27 03:26 UTC, merged